#!/usr/bin/env bash

function gvm_implode() {
  if [ -n "${BASH_VERSION}" ]; then
    read -p "Are you sure? [y/N] " -n 1 -r
  elif [ -n "${ZSH_VERSION}" ]; then
    read -k 1 "REPLY?Are you sure? [y/N] " -r
  fi
  echo
  if [[ ! $REPLY =~ ^[Yy]$ ]]; then
   display_message "Action cancelled"
 else
   (sudo rm -rf "$GVM_ROOT" && display_message "GVM successfully removed") || display_error "Failed to uninstall gvm"
 fi
}
